### ISSUE TITLE
Envio de e-mails

### ISSUE THREAD

**Issue by Marcelo-Theodoro** [Marcelo-Theodoro/web2commerce#12]
Partes do sistemas que terão que enviar e-mail:

- Cadastro de comprador: Confirmação de e-mail. <- Ele pode logara sem confirmar o e-mail.

- Cadastro de lojista: Quando o lojista se cadastrar, ele recebe um e-mail avisando que a conta está em processo de avaliação. Quando o status for alterado, o lojista deve receber um e-mail com o status atual.

(Admin recebe cópias do e-mail quando o lojista se cadastrar)

- Tanto comprador quando lojista vão receber um e-mail quando uma compra for finalizada.
 
- Busca offiline para o Admin
- Atendimento para o Admin

**Comment by lucasm310** [comment]
Teremos que usar o esquema de http://web2py.com/books/default/chapter/34/08/email-and-sms#Using-the-template-system-to-generate-messages para formatar as mensagens de cadastro e pedido.

E usar um script de background para enviar conforme uma fila

**Comment by Marcelo-Theodoro** [comment]
> python web2py.py -S web2commerce -M -R applications/web2commerce/private/fila_emails.py

Comando para iniciar a fila de emails.

**Comment by Marcelo-Theodoro** [comment]
Criei um form lá em c='infos', f='fale_conosco'. Só precisa adicionar ele na view, segue o mesmo estilo do que já estava.

Em infos/atendimento, está redirecionando para infos/fale_conosco
