### ISSUE TITLE
Lojista: Campo de busca em todos_produtos

### ISSUE THREAD

**Issue by Marcelo-Theodoro** [Marcelo-Theodoro/web2commerce#50]

**Comment by Marcelo-Theodoro** [comment]
>É preciso incluir opção para o usuário pesquisar um produto dentro do seu acervo por Grupo, Titulo, Autor, Editora ou Faixa de Preço caso o mesmo precise fazer uma alteração de preço ou algo que esteja cadastrado errado.
Imagem em um acervo com 40 mil produtos como o usuário vai encontrar e fazer alteração no cadastro sem um sistema de pesquisa dentro do seu painel.

**Comment by lucasm310** [comment]
@Marcelo-Theodoro Bug em na pesquisa por titulo

**Comment by Marcelo-Theodoro** [comment]
@lucasm310 Já tem preco e disponibilidade lá.
