### ISSUE TITLE
info: fale_conosco ajustar o form.

### ISSUE THREAD

**Issue by lucasm310** [Marcelo-Theodoro/web2commerce#54]
Campos Empresa, cidade, telefone, uf, cidade são opcionais.
Quando der o submit mostrar mensagem que foi enviado com sucesso.
Centralizar campos na views.

**Comment by Marcelo-Theodoro** [comment]
Caso a mensagem tenha sido enviada com sucesso, é adicionado o argumento ```sucesso``` na url. Caso contrario, é adicionado ```erro```.

**Comment by lucasm310** [comment]
Diminuir o tamanho dos campos
