### ISSUE TITLE
info: venda de acervo form para enviar email.

### ISSUE THREAD

**Issue by lucasm310** [Marcelo-Theodoro/web2commerce#56]
Quando o cliente clica sobre o botão ENVIAR é enviada mensagem para todos os lojistas os LOJISTAS com status ATIVADO.
![2](https://cloud.githubusercontent.com/assets/13260977/14017344/93d36848-f1a5-11e5-88c6-987675e85fbf.png)

**Comment by Marcelo-Theodoro** [comment]
Necessário estar logado.

**Comment by Marcelo-Theodoro** [comment]
@lucasm310 View pra isso aqui também.
