### ISSUE TITLE
Tela MEUS PEDIDOS

### ISSUE THREAD

**Issue by lucasm310** [Marcelo-Theodoro/web2commerce#70]
1) Na tela de MEUS PEDIDOS precisa informar o NUMERO DO PEDIDO, DATA e LOJISTA com opção do link VER MAIS DETALHES.
2) Precisa ter o numero do pedido na tela junto com a data.
3) Na tela de consulta do pedido a data esta no formato errado.

**Comment by lucasm310** [comment]
@Marcelo-Theodoro Preciso do id do lojista em default/pedido

**Comment by Marcelo-Theodoro** [comment]
@lucasm310 Não é uma boa ideia. Seria necessário fazer muitas consultas no BD pra isso.

Basicamente uma pra cada lojista em cada pedido. Posso fazer se considerar necessário.

**Comment by lucasm310** [comment]
Precisa incluir os dados do cliente para o mesmo ver para qual endereço escolheu o envio do produto
